---
 - name: crete users
   hosts: all
   become: yes
   remote_user: imene
   roles:
    - user
  
- name: install serveur web 
   hosts: web
   roles:
    - webserver
    
- name: install DataBase
  hosts: db
  roles:
    - database
